# http://wiki.ros.org/costmap_2d
footprint: [[-0.175, -0.175], [-0.175, 0.175], [0.175, 0.175], [0.175, -0.175]]
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.4

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

# layer definitions
# http://wiki.ros.org/costmap_2d/hydro/staticmap
static:
    map_topic: map
    subscribe_to_updates: true

# http://wiki.ros.org/costmap_2d/hydro/obstacles
obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

# http://wiki.ros.org/costmap_2d/hydro/inflation
inflation:
    inflation_radius: 0.2