#
# http://www.ros.org/wiki/gmapping
#


throttle_scans:       1
base_frame:           base_footprint
map_frame:            map
odom_frame:           odom
map_update_interval:  5.0 

# Unset maxUrange and maxRange and it will autodetect
maxUrange:            5.0 #3.5 #3.0 #4.0
sigma:                0.05 #0.025 #0.1 #0.05
kernelSize:           1 
lstep:                0.05
astep:                0.05
iterations:           5 
lsigma:               0.075
ogain:                3.0
lskip:                0

minimumScore:         50.0 #100.0 #50.0

srr:                  0.1
srt:                  0.2
str:                  0.1
stt:                  0.2

linearUpdate:         1.0      
angularUpdate:        0.5 #0.25 #0.5 
temporalUpdate:      -1.0    

resampleThreshold:    0.5    
particles:            30 #100 #1 #30

# Initial Map Size & Resolution
xmin:                -2.0
ymin:                -2.0
xmax:                 2.0
ymax:                 2.0
delta:                0.05

llsamplerange:        0.01           
llsamplestep:         0.01
lasamplerange:        0.005  
lasamplestep:         0.005

transform_publish_period:  0.05       
occ_thresh:           0.25
maxRange:             5.0
